---
- name: Include role vars
  ansible.builtin.include_vars:
    dir: "{{ role_path }}/vars"
    extensions: ["yml", "yaml"]

- name: Apply Docker setup
  ansible.builtin.import_role:
    name: geerlingguy.docker
